/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common_proto.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "common_proto.pb-c.h"
void   account__init
                     (Account         *message)
{
  static const Account init_value = ACCOUNT__INIT;
  *message = init_value;
}
size_t account__get_packed_size
                     (const Account *message)
{
  assert(message->base.descriptor == &account__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t account__pack
                     (const Account *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &account__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t account__pack_to_buffer
                     (const Account *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &account__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Account *
       account__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Account *)
     protobuf_c_message_unpack (&account__descriptor,
                                allocator, len, data);
}
void   account__free_unpacked
                     (Account *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &account__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cpuparameter__init
                     (CPUParameter         *message)
{
  static const CPUParameter init_value = CPUPARAMETER__INIT;
  *message = init_value;
}
size_t cpuparameter__get_packed_size
                     (const CPUParameter *message)
{
  assert(message->base.descriptor == &cpuparameter__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cpuparameter__pack
                     (const CPUParameter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cpuparameter__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cpuparameter__pack_to_buffer
                     (const CPUParameter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cpuparameter__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CPUParameter *
       cpuparameter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CPUParameter *)
     protobuf_c_message_unpack (&cpuparameter__descriptor,
                                allocator, len, data);
}
void   cpuparameter__free_unpacked
                     (CPUParameter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cpuparameter__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cpuscheduler__init
                     (CPUScheduler         *message)
{
  static const CPUScheduler init_value = CPUSCHEDULER__INIT;
  *message = init_value;
}
size_t cpuscheduler__get_packed_size
                     (const CPUScheduler *message)
{
  assert(message->base.descriptor == &cpuscheduler__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cpuscheduler__pack
                     (const CPUScheduler *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cpuscheduler__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cpuscheduler__pack_to_buffer
                     (const CPUScheduler *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cpuscheduler__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CPUScheduler *
       cpuscheduler__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CPUScheduler *)
     protobuf_c_message_unpack (&cpuscheduler__descriptor,
                                allocator, len, data);
}
void   cpuscheduler__free_unpacked
                     (CPUScheduler *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cpuscheduler__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   device__init
                     (Device         *message)
{
  static const Device init_value = DEVICE__INIT;
  *message = init_value;
}
size_t device__get_packed_size
                     (const Device *message)
{
  assert(message->base.descriptor == &device__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device__pack
                     (const Device *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device__pack_to_buffer
                     (const Device *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Device *
       device__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Device *)
     protobuf_c_message_unpack (&device__descriptor,
                                allocator, len, data);
}
void   device__free_unpacked
                     (Device *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sign_param__init
                     (SignParam         *message)
{
  static const SignParam init_value = SIGN_PARAM__INIT;
  *message = init_value;
}
size_t sign_param__get_packed_size
                     (const SignParam *message)
{
  assert(message->base.descriptor == &sign_param__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sign_param__pack
                     (const SignParam *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sign_param__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sign_param__pack_to_buffer
                     (const SignParam *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sign_param__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SignParam *
       sign_param__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SignParam *)
     protobuf_c_message_unpack (&sign_param__descriptor,
                                allocator, len, data);
}
void   sign_param__free_unpacked
                     (SignParam *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sign_param__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   station_lane_light_config__init
                     (StationLaneLightConfig         *message)
{
  static const StationLaneLightConfig init_value = STATION_LANE_LIGHT_CONFIG__INIT;
  *message = init_value;
}
size_t station_lane_light_config__get_packed_size
                     (const StationLaneLightConfig *message)
{
  assert(message->base.descriptor == &station_lane_light_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t station_lane_light_config__pack
                     (const StationLaneLightConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &station_lane_light_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t station_lane_light_config__pack_to_buffer
                     (const StationLaneLightConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &station_lane_light_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StationLaneLightConfig *
       station_lane_light_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StationLaneLightConfig *)
     protobuf_c_message_unpack (&station_lane_light_config__descriptor,
                                allocator, len, data);
}
void   station_lane_light_config__free_unpacked
                     (StationLaneLightConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &station_lane_light_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   meter_item__init
                     (MeterItem         *message)
{
  static const MeterItem init_value = METER_ITEM__INIT;
  *message = init_value;
}
size_t meter_item__get_packed_size
                     (const MeterItem *message)
{
  assert(message->base.descriptor == &meter_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meter_item__pack
                     (const MeterItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meter_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meter_item__pack_to_buffer
                     (const MeterItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meter_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MeterItem *
       meter_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MeterItem *)
     protobuf_c_message_unpack (&meter_item__descriptor,
                                allocator, len, data);
}
void   meter_item__free_unpacked
                     (MeterItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meter_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   station__init
                     (Station         *message)
{
  static const Station init_value = STATION__INIT;
  *message = init_value;
}
size_t station__get_packed_size
                     (const Station *message)
{
  assert(message->base.descriptor == &station__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t station__pack
                     (const Station *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &station__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t station__pack_to_buffer
                     (const Station *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &station__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Station *
       station__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Station *)
     protobuf_c_message_unpack (&station__descriptor,
                                allocator, len, data);
}
void   station__free_unpacked
                     (Station *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &station__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   accessory__init
                     (Accessory         *message)
{
  static const Accessory init_value = ACCESSORY__INIT;
  *message = init_value;
}
size_t accessory__get_packed_size
                     (const Accessory *message)
{
  assert(message->base.descriptor == &accessory__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t accessory__pack
                     (const Accessory *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &accessory__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t accessory__pack_to_buffer
                     (const Accessory *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &accessory__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Accessory *
       accessory__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Accessory *)
     protobuf_c_message_unpack (&accessory__descriptor,
                                allocator, len, data);
}
void   accessory__free_unpacked
                     (Accessory *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &accessory__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   card_config__init
                     (CardConfig         *message)
{
  static const CardConfig init_value = CARD_CONFIG__INIT;
  *message = init_value;
}
size_t card_config__get_packed_size
                     (const CardConfig *message)
{
  assert(message->base.descriptor == &card_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t card_config__pack
                     (const CardConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &card_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t card_config__pack_to_buffer
                     (const CardConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &card_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CardConfig *
       card_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CardConfig *)
     protobuf_c_message_unpack (&card_config__descriptor,
                                allocator, len, data);
}
void   card_config__free_unpacked
                     (CardConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &card_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mtfcphase_gate_config__init
                     (MTFCPhaseGateConfig         *message)
{
  static const MTFCPhaseGateConfig init_value = MTFCPHASE_GATE_CONFIG__INIT;
  *message = init_value;
}
size_t mtfcphase_gate_config__get_packed_size
                     (const MTFCPhaseGateConfig *message)
{
  assert(message->base.descriptor == &mtfcphase_gate_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mtfcphase_gate_config__pack
                     (const MTFCPhaseGateConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mtfcphase_gate_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mtfcphase_gate_config__pack_to_buffer
                     (const MTFCPhaseGateConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mtfcphase_gate_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MTFCPhaseGateConfig *
       mtfcphase_gate_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MTFCPhaseGateConfig *)
     protobuf_c_message_unpack (&mtfcphase_gate_config__descriptor,
                                allocator, len, data);
}
void   mtfcphase_gate_config__free_unpacked
                     (MTFCPhaseGateConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mtfcphase_gate_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hmtime__init
                     (HMTime         *message)
{
  static const HMTime init_value = HMTIME__INIT;
  *message = init_value;
}
size_t hmtime__get_packed_size
                     (const HMTime *message)
{
  assert(message->base.descriptor == &hmtime__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hmtime__pack
                     (const HMTime *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hmtime__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hmtime__pack_to_buffer
                     (const HMTime *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hmtime__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HMTime *
       hmtime__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HMTime *)
     protobuf_c_message_unpack (&hmtime__descriptor,
                                allocator, len, data);
}
void   hmtime__free_unpacked
                     (HMTime *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hmtime__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   active_lamp__init
                     (ActiveLamp         *message)
{
  static const ActiveLamp init_value = ACTIVE_LAMP__INIT;
  *message = init_value;
}
size_t active_lamp__get_packed_size
                     (const ActiveLamp *message)
{
  assert(message->base.descriptor == &active_lamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t active_lamp__pack
                     (const ActiveLamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &active_lamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t active_lamp__pack_to_buffer
                     (const ActiveLamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &active_lamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActiveLamp *
       active_lamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActiveLamp *)
     protobuf_c_message_unpack (&active_lamp__descriptor,
                                allocator, len, data);
}
void   active_lamp__free_unpacked
                     (ActiveLamp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &active_lamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   one_side_lamp_time__init
                     (OneSideLampTime         *message)
{
  static const OneSideLampTime init_value = ONE_SIDE_LAMP_TIME__INIT;
  *message = init_value;
}
size_t one_side_lamp_time__get_packed_size
                     (const OneSideLampTime *message)
{
  assert(message->base.descriptor == &one_side_lamp_time__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t one_side_lamp_time__pack
                     (const OneSideLampTime *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &one_side_lamp_time__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t one_side_lamp_time__pack_to_buffer
                     (const OneSideLampTime *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &one_side_lamp_time__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OneSideLampTime *
       one_side_lamp_time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OneSideLampTime *)
     protobuf_c_message_unpack (&one_side_lamp_time__descriptor,
                                allocator, len, data);
}
void   one_side_lamp_time__free_unpacked
                     (OneSideLampTime *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &one_side_lamp_time__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   one_cycle_lamp_time__init
                     (OneCycleLampTime         *message)
{
  static const OneCycleLampTime init_value = ONE_CYCLE_LAMP_TIME__INIT;
  *message = init_value;
}
size_t one_cycle_lamp_time__get_packed_size
                     (const OneCycleLampTime *message)
{
  assert(message->base.descriptor == &one_cycle_lamp_time__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t one_cycle_lamp_time__pack
                     (const OneCycleLampTime *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &one_cycle_lamp_time__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t one_cycle_lamp_time__pack_to_buffer
                     (const OneCycleLampTime *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &one_cycle_lamp_time__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OneCycleLampTime *
       one_cycle_lamp_time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OneCycleLampTime *)
     protobuf_c_message_unpack (&one_cycle_lamp_time__descriptor,
                                allocator, len, data);
}
void   one_cycle_lamp_time__free_unpacked
                     (OneCycleLampTime *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &one_cycle_lamp_time__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cycle_lamp_form__init
                     (CycleLampForm         *message)
{
  static const CycleLampForm init_value = CYCLE_LAMP_FORM__INIT;
  *message = init_value;
}
size_t cycle_lamp_form__get_packed_size
                     (const CycleLampForm *message)
{
  assert(message->base.descriptor == &cycle_lamp_form__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cycle_lamp_form__pack
                     (const CycleLampForm *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cycle_lamp_form__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cycle_lamp_form__pack_to_buffer
                     (const CycleLampForm *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cycle_lamp_form__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CycleLampForm *
       cycle_lamp_form__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CycleLampForm *)
     protobuf_c_message_unpack (&cycle_lamp_form__descriptor,
                                allocator, len, data);
}
void   cycle_lamp_form__free_unpacked
                     (CycleLampForm *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cycle_lamp_form__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   one_timeline__init
                     (OneTimeline         *message)
{
  static const OneTimeline init_value = ONE_TIMELINE__INIT;
  *message = init_value;
}
size_t one_timeline__get_packed_size
                     (const OneTimeline *message)
{
  assert(message->base.descriptor == &one_timeline__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t one_timeline__pack
                     (const OneTimeline *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &one_timeline__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t one_timeline__pack_to_buffer
                     (const OneTimeline *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &one_timeline__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OneTimeline *
       one_timeline__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OneTimeline *)
     protobuf_c_message_unpack (&one_timeline__descriptor,
                                allocator, len, data);
}
void   one_timeline__free_unpacked
                     (OneTimeline *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &one_timeline__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   day_time_line__init
                     (DayTimeLine         *message)
{
  static const DayTimeLine init_value = DAY_TIME_LINE__INIT;
  *message = init_value;
}
size_t day_time_line__get_packed_size
                     (const DayTimeLine *message)
{
  assert(message->base.descriptor == &day_time_line__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t day_time_line__pack
                     (const DayTimeLine *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &day_time_line__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t day_time_line__pack_to_buffer
                     (const DayTimeLine *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &day_time_line__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DayTimeLine *
       day_time_line__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DayTimeLine *)
     protobuf_c_message_unpack (&day_time_line__descriptor,
                                allocator, len, data);
}
void   day_time_line__free_unpacked
                     (DayTimeLine *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &day_time_line__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   time_lamp_form__init
                     (TimeLampForm         *message)
{
  static const TimeLampForm init_value = TIME_LAMP_FORM__INIT;
  *message = init_value;
}
size_t time_lamp_form__get_packed_size
                     (const TimeLampForm *message)
{
  assert(message->base.descriptor == &time_lamp_form__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_lamp_form__pack
                     (const TimeLampForm *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_lamp_form__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_lamp_form__pack_to_buffer
                     (const TimeLampForm *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_lamp_form__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimeLampForm *
       time_lamp_form__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimeLampForm *)
     protobuf_c_message_unpack (&time_lamp_form__descriptor,
                                allocator, len, data);
}
void   time_lamp_form__free_unpacked
                     (TimeLampForm *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &time_lamp_form__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   day_lamp_form__init
                     (DayLampForm         *message)
{
  static const DayLampForm init_value = DAY_LAMP_FORM__INIT;
  *message = init_value;
}
size_t day_lamp_form__get_packed_size
                     (const DayLampForm *message)
{
  assert(message->base.descriptor == &day_lamp_form__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t day_lamp_form__pack
                     (const DayLampForm *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &day_lamp_form__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t day_lamp_form__pack_to_buffer
                     (const DayLampForm *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &day_lamp_form__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DayLampForm *
       day_lamp_form__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DayLampForm *)
     protobuf_c_message_unpack (&day_lamp_form__descriptor,
                                allocator, len, data);
}
void   day_lamp_form__free_unpacked
                     (DayLampForm *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &day_lamp_form__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lane_state__init
                     (LaneState         *message)
{
  static const LaneState init_value = LANE_STATE__INIT;
  *message = init_value;
}
size_t lane_state__get_packed_size
                     (const LaneState *message)
{
  assert(message->base.descriptor == &lane_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lane_state__pack
                     (const LaneState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lane_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lane_state__pack_to_buffer
                     (const LaneState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lane_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LaneState *
       lane_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LaneState *)
     protobuf_c_message_unpack (&lane_state__descriptor,
                                allocator, len, data);
}
void   lane_state__free_unpacked
                     (LaneState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lane_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   device_state__init
                     (DeviceState         *message)
{
  static const DeviceState init_value = DEVICE_STATE__INIT;
  *message = init_value;
}
size_t device_state__get_packed_size
                     (const DeviceState *message)
{
  assert(message->base.descriptor == &device_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_state__pack
                     (const DeviceState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_state__pack_to_buffer
                     (const DeviceState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceState *
       device_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceState *)
     protobuf_c_message_unpack (&device_state__descriptor,
                                allocator, len, data);
}
void   device_state__free_unpacked
                     (DeviceState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   status_code__init
                     (StatusCode         *message)
{
  static const StatusCode init_value = STATUS_CODE__INIT;
  *message = init_value;
}
size_t status_code__get_packed_size
                     (const StatusCode *message)
{
  assert(message->base.descriptor == &status_code__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t status_code__pack
                     (const StatusCode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &status_code__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t status_code__pack_to_buffer
                     (const StatusCode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &status_code__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StatusCode *
       status_code__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StatusCode *)
     protobuf_c_message_unpack (&status_code__descriptor,
                                allocator, len, data);
}
void   status_code__free_unpacked
                     (StatusCode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &status_code__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor account__field_descriptors[5] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Account, userid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "userName",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Account, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "role",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Account, role),
    &account_role__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "createDate",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Account, createdate),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isCurrentAccount",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Account, iscurrentaccount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned account__field_indices_by_name[] = {
  3,   /* field[3] = createDate */
  4,   /* field[4] = isCurrentAccount */
  2,   /* field[2] = role */
  0,   /* field[0] = userId */
  1,   /* field[1] = userName */
};
static const ProtobufCIntRange account__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor account__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Account",
  "Account",
  "Account",
  "",
  sizeof(Account),
  5,
  account__field_descriptors,
  account__field_indices_by_name,
  1,  account__number_ranges,
  (ProtobufCMessageInit) account__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define cpuparameter__field_descriptors NULL
#define cpuparameter__field_indices_by_name NULL
#define cpuparameter__number_ranges NULL
const ProtobufCMessageDescriptor cpuparameter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CPUParameter",
  "CPUParameter",
  "CPUParameter",
  "",
  sizeof(CPUParameter),
  0,
  cpuparameter__field_descriptors,
  cpuparameter__field_indices_by_name,
  0,  cpuparameter__number_ranges,
  (ProtobufCMessageInit) cpuparameter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define cpuscheduler__field_descriptors NULL
#define cpuscheduler__field_indices_by_name NULL
#define cpuscheduler__number_ranges NULL
const ProtobufCMessageDescriptor cpuscheduler__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CPUScheduler",
  "CPUScheduler",
  "CPUScheduler",
  "",
  sizeof(CPUScheduler),
  0,
  cpuscheduler__field_descriptors,
  cpuscheduler__field_indices_by_name,
  0,  cpuscheduler__number_ranges,
  (ProtobufCMessageInit) cpuscheduler__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device__field_descriptors[8] =
{
  {
    "deviceId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Device, deviceid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceType",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Device, devicetype),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceState",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Device, devicestate),
    &device_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stationName",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Device, stationname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hardwareId",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Device, hardwareid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numPhase",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Device, numphase),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Device, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Device, log),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device__field_indices_by_name[] = {
  0,   /* field[0] = deviceId */
  2,   /* field[2] = deviceState */
  1,   /* field[1] = deviceType */
  4,   /* field[4] = hardwareId */
  6,   /* field[6] = lat */
  7,   /* field[7] = log */
  5,   /* field[5] = numPhase */
  3,   /* field[3] = stationName */
};
static const ProtobufCIntRange device__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor device__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Device",
  "Device",
  "Device",
  "",
  sizeof(Device),
  8,
  device__field_descriptors,
  device__field_indices_by_name,
  1,  device__number_ranges,
  (ProtobufCMessageInit) device__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sign_param__field_descriptors[4] =
{
  {
    "channel",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SignParam, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SignParam, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SignParam, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SignParam, text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sign_param__field_indices_by_name[] = {
  0,   /* field[0] = channel */
  3,   /* field[3] = text */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
};
static const ProtobufCIntRange sign_param__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sign_param__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SignParam",
  "SignParam",
  "SignParam",
  "",
  sizeof(SignParam),
  4,
  sign_param__field_descriptors,
  sign_param__field_indices_by_name,
  1,  sign_param__number_ranges,
  (ProtobufCMessageInit) sign_param__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor station_lane_light_config__field_descriptors[9] =
{
  {
    "countdown",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StationLaneLightConfig, countdown),
    &sign_param__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trafficLight",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StationLaneLightConfig, trafficlight),
    &sign_param__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "walking",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StationLaneLightConfig, walking),
    &sign_param__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "railway",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StationLaneLightConfig, railway),
    &sign_param__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "turnRight",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StationLaneLightConfig, turnright),
    &sign_param__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goAhead",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StationLaneLightConfig, goahead),
    &sign_param__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "turnLeft",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StationLaneLightConfig, turnleft),
    &sign_param__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StationLaneLightConfig, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StationLaneLightConfig, label),
    &sign_param__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned station_lane_light_config__field_indices_by_name[] = {
  0,   /* field[0] = countdown */
  5,   /* field[5] = goAhead */
  7,   /* field[7] = index */
  8,   /* field[8] = label */
  3,   /* field[3] = railway */
  1,   /* field[1] = trafficLight */
  6,   /* field[6] = turnLeft */
  4,   /* field[4] = turnRight */
  2,   /* field[2] = walking */
};
static const ProtobufCIntRange station_lane_light_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor station_lane_light_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StationLaneLightConfig",
  "StationLaneLightConfig",
  "StationLaneLightConfig",
  "",
  sizeof(StationLaneLightConfig),
  9,
  station_lane_light_config__field_descriptors,
  station_lane_light_config__field_indices_by_name,
  1,  station_lane_light_config__number_ranges,
  (ProtobufCMessageInit) station_lane_light_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meter_item__field_descriptors[4] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MeterItem, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MeterItem, time),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(MeterItem, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MeterItem, label),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meter_item__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = index */
  3,   /* field[3] = label */
  1,   /* field[1] = time */
};
static const ProtobufCIntRange meter_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor meter_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MeterItem",
  "MeterItem",
  "MeterItem",
  "",
  sizeof(MeterItem),
  4,
  meter_item__field_descriptors,
  meter_item__field_indices_by_name,
  1,  meter_item__number_ranges,
  (ProtobufCMessageInit) meter_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor station__field_descriptors[21] =
{
  {
    "stationId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Station, stationid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Station, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Station, device),
    &device__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stationLat",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Station, stationlat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stationLong",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Station, stationlong),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numPhase",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Station, numphase),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "laneLightConfig",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Station, n_lanelightconfig),
    offsetof(Station, lanelightconfig),
    &station_lane_light_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "background",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Station, background),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hardwareId",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Station, hardwareid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Station, firmware),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "createDate",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Station, createdate),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numCard",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Station, numcard),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errorStatus",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Station, errorstatus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errorStatusNote",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Station, errorstatusnote),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connectionState",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Station, connectionstate),
    &connection_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isOn",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Station, ison),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "activeBegin",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Station, activebegin),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "activeEnd",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Station, activeend),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "meterItems",
    19,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Station, n_meteritems),
    offsetof(Station, meteritems),
    &meter_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceId",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Station, deviceid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Station, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned station__field_indices_by_name[] = {
  16,   /* field[16] = activeBegin */
  17,   /* field[17] = activeEnd */
  7,   /* field[7] = background */
  14,   /* field[14] = connectionState */
  10,   /* field[10] = createDate */
  2,   /* field[2] = device */
  19,   /* field[19] = deviceId */
  12,   /* field[12] = errorStatus */
  13,   /* field[13] = errorStatusNote */
  9,   /* field[9] = firmware */
  8,   /* field[8] = hardwareId */
  15,   /* field[15] = isOn */
  6,   /* field[6] = laneLightConfig */
  18,   /* field[18] = meterItems */
  20,   /* field[20] = mode */
  1,   /* field[1] = name */
  11,   /* field[11] = numCard */
  5,   /* field[5] = numPhase */
  0,   /* field[0] = stationId */
  3,   /* field[3] = stationLat */
  4,   /* field[4] = stationLong */
};
static const ProtobufCIntRange station__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 21 }
};
const ProtobufCMessageDescriptor station__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Station",
  "Station",
  "Station",
  "",
  sizeof(Station),
  21,
  station__field_descriptors,
  station__field_indices_by_name,
  1,  station__number_ranges,
  (ProtobufCMessageInit) station__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor accessory__field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accessory, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accessory, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accessory, model),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "madeBy",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accessory, madeby),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accessory, position),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "installedPos",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accessory, installedpos),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "installedDate",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accessory, installeddate),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accessory, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stationId",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accessory, stationid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned accessory__field_indices_by_name[] = {
  0,   /* field[0] = id */
  6,   /* field[6] = installedDate */
  5,   /* field[5] = installedPos */
  3,   /* field[3] = madeBy */
  2,   /* field[2] = model */
  1,   /* field[1] = name */
  4,   /* field[4] = position */
  8,   /* field[8] = stationId */
  7,   /* field[7] = status */
};
static const ProtobufCIntRange accessory__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor accessory__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Accessory",
  "Accessory",
  "Accessory",
  "",
  sizeof(Accessory),
  9,
  accessory__field_descriptors,
  accessory__field_indices_by_name,
  1,  accessory__number_ranges,
  (ProtobufCMessageInit) accessory__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor card_config__field_descriptors[4] =
{
  {
    "serialNumber",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CardConfig, serialnumber),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imei",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CardConfig, imei),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phase",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CardConfig, phase),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isRailwayEnabled",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CardConfig, israilwayenabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned card_config__field_indices_by_name[] = {
  1,   /* field[1] = imei */
  3,   /* field[3] = isRailwayEnabled */
  2,   /* field[2] = phase */
  0,   /* field[0] = serialNumber */
};
static const ProtobufCIntRange card_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor card_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CardConfig",
  "CardConfig",
  "CardConfig",
  "",
  sizeof(CardConfig),
  4,
  card_config__field_descriptors,
  card_config__field_indices_by_name,
  1,  card_config__number_ranges,
  (ProtobufCMessageInit) card_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mtfcphase_gate_config__field_descriptors[1] =
{
  {
    "pin",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(MTFCPhaseGateConfig, n_pin),
    offsetof(MTFCPhaseGateConfig, pin),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mtfcphase_gate_config__field_indices_by_name[] = {
  0,   /* field[0] = pin */
};
static const ProtobufCIntRange mtfcphase_gate_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mtfcphase_gate_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MTFCPhaseGateConfig",
  "MTFCPhaseGateConfig",
  "MTFCPhaseGateConfig",
  "",
  sizeof(MTFCPhaseGateConfig),
  1,
  mtfcphase_gate_config__field_descriptors,
  mtfcphase_gate_config__field_indices_by_name,
  1,  mtfcphase_gate_config__number_ranges,
  (ProtobufCMessageInit) mtfcphase_gate_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hmtime__field_descriptors[2] =
{
  {
    "hour",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(HMTime, hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minute",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(HMTime, minute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hmtime__field_indices_by_name[] = {
  0,   /* field[0] = hour */
  1,   /* field[1] = minute */
};
static const ProtobufCIntRange hmtime__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hmtime__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HMTime",
  "HMTime",
  "HMTime",
  "",
  sizeof(HMTime),
  2,
  hmtime__field_descriptors,
  hmtime__field_indices_by_name,
  1,  hmtime__number_ranges,
  (ProtobufCMessageInit) hmtime__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor active_lamp__field_descriptors[2] =
{
  {
    "begin",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActiveLamp, begin),
    &hmtime__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ActiveLamp, end),
    &hmtime__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned active_lamp__field_indices_by_name[] = {
  0,   /* field[0] = begin */
  1,   /* field[1] = end */
};
static const ProtobufCIntRange active_lamp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor active_lamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActiveLamp",
  "ActiveLamp",
  "ActiveLamp",
  "",
  sizeof(ActiveLamp),
  2,
  active_lamp__field_descriptors,
  active_lamp__field_indices_by_name,
  1,  active_lamp__number_ranges,
  (ProtobufCMessageInit) active_lamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor one_side_lamp_time__field_descriptors[7] =
{
  {
    "t_green",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OneSideLampTime, t_green),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t_yellow",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OneSideLampTime, t_yellow),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t_red",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OneSideLampTime, t_red),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t_start_green",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OneSideLampTime, t_start_green),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t_end_green",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OneSideLampTime, t_end_green),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t_start_yellow",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OneSideLampTime, t_start_yellow),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t_end_yellow",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OneSideLampTime, t_end_yellow),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned one_side_lamp_time__field_indices_by_name[] = {
  4,   /* field[4] = t_end_green */
  6,   /* field[6] = t_end_yellow */
  0,   /* field[0] = t_green */
  2,   /* field[2] = t_red */
  3,   /* field[3] = t_start_green */
  5,   /* field[5] = t_start_yellow */
  1,   /* field[1] = t_yellow */
};
static const ProtobufCIntRange one_side_lamp_time__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor one_side_lamp_time__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OneSideLampTime",
  "OneSideLampTime",
  "OneSideLampTime",
  "",
  sizeof(OneSideLampTime),
  7,
  one_side_lamp_time__field_descriptors,
  one_side_lamp_time__field_indices_by_name,
  1,  one_side_lamp_time__number_ranges,
  (ProtobufCMessageInit) one_side_lamp_time__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor one_cycle_lamp_time__field_descriptors[5] =
{
  {
    "num_side_used",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OneCycleLampTime, num_side_used),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "period_crossroads",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OneCycleLampTime, period_crossroads),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "side",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OneCycleLampTime, n_side),
    offsetof(OneCycleLampTime, side),
    &one_side_lamp_time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clearance_time_crossroads",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OneCycleLampTime, clearance_time_crossroads),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isModified",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(OneCycleLampTime, ismodified),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned one_cycle_lamp_time__field_indices_by_name[] = {
  3,   /* field[3] = clearance_time_crossroads */
  4,   /* field[4] = isModified */
  0,   /* field[0] = num_side_used */
  1,   /* field[1] = period_crossroads */
  2,   /* field[2] = side */
};
static const ProtobufCIntRange one_cycle_lamp_time__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor one_cycle_lamp_time__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OneCycleLampTime",
  "OneCycleLampTime",
  "OneCycleLampTime",
  "",
  sizeof(OneCycleLampTime),
  5,
  one_cycle_lamp_time__field_descriptors,
  one_cycle_lamp_time__field_indices_by_name,
  1,  one_cycle_lamp_time__number_ranges,
  (ProtobufCMessageInit) one_cycle_lamp_time__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cycle_lamp_form__field_descriptors[1] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CycleLampForm, n_index),
    offsetof(CycleLampForm, index),
    &one_cycle_lamp_time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cycle_lamp_form__field_indices_by_name[] = {
  0,   /* field[0] = index */
};
static const ProtobufCIntRange cycle_lamp_form__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cycle_lamp_form__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CycleLampForm",
  "CycleLampForm",
  "CycleLampForm",
  "",
  sizeof(CycleLampForm),
  1,
  cycle_lamp_form__field_descriptors,
  cycle_lamp_form__field_indices_by_name,
  1,  cycle_lamp_form__number_ranges,
  (ProtobufCMessageInit) cycle_lamp_form__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor one_timeline__field_descriptors[2] =
{
  {
    "t_begin_apply",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OneTimeline, t_begin_apply),
    &hmtime__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index_cycle_form",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OneTimeline, index_cycle_form),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned one_timeline__field_indices_by_name[] = {
  1,   /* field[1] = index_cycle_form */
  0,   /* field[0] = t_begin_apply */
};
static const ProtobufCIntRange one_timeline__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor one_timeline__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OneTimeline",
  "OneTimeline",
  "OneTimeline",
  "",
  sizeof(OneTimeline),
  2,
  one_timeline__field_descriptors,
  one_timeline__field_indices_by_name,
  1,  one_timeline__number_ranges,
  (ProtobufCMessageInit) one_timeline__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor day_time_line__field_descriptors[1] =
{
  {
    "selectPoint",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DayTimeLine, n_selectpoint),
    offsetof(DayTimeLine, selectpoint),
    &one_timeline__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned day_time_line__field_indices_by_name[] = {
  0,   /* field[0] = selectPoint */
};
static const ProtobufCIntRange day_time_line__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor day_time_line__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DayTimeLine",
  "DayTimeLine",
  "DayTimeLine",
  "",
  sizeof(DayTimeLine),
  1,
  day_time_line__field_descriptors,
  day_time_line__field_indices_by_name,
  1,  day_time_line__number_ranges,
  (ProtobufCMessageInit) day_time_line__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor time_lamp_form__field_descriptors[1] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TimeLampForm, n_index),
    offsetof(TimeLampForm, index),
    &day_time_line__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_lamp_form__field_indices_by_name[] = {
  0,   /* field[0] = index */
};
static const ProtobufCIntRange time_lamp_form__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor time_lamp_form__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimeLampForm",
  "TimeLampForm",
  "TimeLampForm",
  "",
  sizeof(TimeLampForm),
  1,
  time_lamp_form__field_descriptors,
  time_lamp_form__field_indices_by_name,
  1,  time_lamp_form__number_ranges,
  (ProtobufCMessageInit) time_lamp_form__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor day_lamp_form__field_descriptors[1] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DayLampForm, n_index),
    offsetof(DayLampForm, index),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned day_lamp_form__field_indices_by_name[] = {
  0,   /* field[0] = index */
};
static const ProtobufCIntRange day_lamp_form__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor day_lamp_form__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DayLampForm",
  "DayLampForm",
  "DayLampForm",
  "",
  sizeof(DayLampForm),
  1,
  day_lamp_form__field_descriptors,
  day_lamp_form__field_indices_by_name,
  1,  day_lamp_form__number_ranges,
  (ProtobufCMessageInit) day_lamp_form__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lane_state__field_descriptors[3] =
{
  {
    "walkingState",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LaneState, walkingstate),
    &walking_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lightState",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LaneState, lightstate),
    &traffic_light_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counter",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LaneState, counter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lane_state__field_indices_by_name[] = {
  2,   /* field[2] = counter */
  1,   /* field[1] = lightState */
  0,   /* field[0] = walkingState */
};
static const ProtobufCIntRange lane_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor lane_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LaneState",
  "LaneState",
  "LaneState",
  "",
  sizeof(LaneState),
  3,
  lane_state__field_descriptors,
  lane_state__field_indices_by_name,
  1,  lane_state__number_ranges,
  (ProtobufCMessageInit) lane_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device_state__field_descriptors[16] =
{
  {
    "connectionState",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DeviceState, connectionstate),
    &connection_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_phase",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceState, num_phase),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signal",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DeviceState, n_signal),
    offsetof(DeviceState, signal),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mapping",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DeviceState, n_mapping),
    offsetof(DeviceState, mapping),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "countdown",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DeviceState, n_countdown),
    offsetof(DeviceState, countdown),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rtc_epoch",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceState, rtc_epoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_sensor",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DeviceState, n_output_sensor),
    offsetof(DeviceState, output_sensor),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "walking_signal",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceState, walking_signal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "railway_signal",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceState, railway_signal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_active_mode",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DeviceState, cpu_active_mode),
    &mtfcmain_work_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input_hardware",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceState, input_hardware),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input_software",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceState, input_software),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idx_time_form",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceState, idx_time_form),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idx_timeline",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceState, idx_timeline),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idx_cycle_form",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceState, idx_cycle_form),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "laneState",
    16,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DeviceState, n_lanestate),
    offsetof(DeviceState, lanestate),
    &lane_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_state__field_indices_by_name[] = {
  0,   /* field[0] = connectionState */
  4,   /* field[4] = countdown */
  9,   /* field[9] = cpu_active_mode */
  14,   /* field[14] = idx_cycle_form */
  12,   /* field[12] = idx_time_form */
  13,   /* field[13] = idx_timeline */
  10,   /* field[10] = input_hardware */
  11,   /* field[11] = input_software */
  15,   /* field[15] = laneState */
  3,   /* field[3] = mapping */
  1,   /* field[1] = num_phase */
  6,   /* field[6] = output_sensor */
  8,   /* field[8] = railway_signal */
  5,   /* field[5] = rtc_epoch */
  2,   /* field[2] = signal */
  7,   /* field[7] = walking_signal */
};
static const ProtobufCIntRange device_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor device_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceState",
  "DeviceState",
  "DeviceState",
  "",
  sizeof(DeviceState),
  16,
  device_state__field_descriptors,
  device_state__field_indices_by_name,
  1,  device_state__number_ranges,
  (ProtobufCMessageInit) device_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor status_code__field_descriptors[2] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StatusCode, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatusCode, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned status_code__field_indices_by_name[] = {
  1,   /* field[1] = code */
  0,   /* field[0] = message */
};
static const ProtobufCIntRange status_code__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor status_code__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StatusCode",
  "StatusCode",
  "StatusCode",
  "",
  sizeof(StatusCode),
  2,
  status_code__field_descriptors,
  status_code__field_indices_by_name,
  1,  status_code__number_ranges,
  (ProtobufCMessageInit) status_code__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue device_type__enum_values_by_number[6] =
{
  { "MTFC_AC", "DEVICE_TYPE__MTFC_AC", 0 },
  { "MTFC_DC_24", "DEVICE_TYPE__MTFC_DC_24", 1 },
  { "MTFC_DC_36", "DEVICE_TYPE__MTFC_DC_36", 2 },
  { "MTFC_DC_48", "DEVICE_TYPE__MTFC_DC_48", 3 },
  { "MTFC_SOLAR", "DEVICE_TYPE__MTFC_SOLAR", 4 },
  { "MTFC_SMS_CONTROLLER", "DEVICE_TYPE__MTFC_SMS_CONTROLLER", 5 },
};
static const ProtobufCIntRange device_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex device_type__enum_values_by_name[6] =
{
  { "MTFC_AC", 0 },
  { "MTFC_DC_24", 1 },
  { "MTFC_DC_36", 2 },
  { "MTFC_DC_48", 3 },
  { "MTFC_SMS_CONTROLLER", 5 },
  { "MTFC_SOLAR", 4 },
};
const ProtobufCEnumDescriptor device_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DeviceType",
  "DeviceType",
  "DeviceType",
  "",
  6,
  device_type__enum_values_by_number,
  6,
  device_type__enum_values_by_name,
  1,
  device_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue account_role__enum_values_by_number[3] =
{
  { "NONE", "ACCOUNT_ROLE__NONE", 0 },
  { "ADMIN", "ACCOUNT_ROLE__ADMIN", 1 },
  { "OPERATOR", "ACCOUNT_ROLE__OPERATOR", 2 },
};
static const ProtobufCIntRange account_role__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex account_role__enum_values_by_name[3] =
{
  { "ADMIN", 1 },
  { "NONE", 0 },
  { "OPERATOR", 2 },
};
const ProtobufCEnumDescriptor account_role__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AccountRole",
  "AccountRole",
  "AccountRole",
  "",
  3,
  account_role__enum_values_by_number,
  3,
  account_role__enum_values_by_name,
  1,
  account_role__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue connection_state__enum_values_by_number[2] =
{
  { "CONNECTION_OFFLINE", "CONNECTION_STATE__CONNECTION_OFFLINE", 0 },
  { "CONNECTION_ONLINE", "CONNECTION_STATE__CONNECTION_ONLINE", 1 },
};
static const ProtobufCIntRange connection_state__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex connection_state__enum_values_by_name[2] =
{
  { "CONNECTION_OFFLINE", 0 },
  { "CONNECTION_ONLINE", 1 },
};
const ProtobufCEnumDescriptor connection_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ConnectionState",
  "ConnectionState",
  "ConnectionState",
  "",
  2,
  connection_state__enum_values_by_number,
  2,
  connection_state__enum_values_by_name,
  1,
  connection_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue mtfcmain_work_state__enum_values_by_number[5] =
{
  { "MTFC_STATE_off", "MTFCMAIN_WORK_STATE__MTFC_STATE_off", 0 },
  { "MTFC_STATE_AUTO", "MTFCMAIN_WORK_STATE__MTFC_STATE_AUTO", 1 },
  { "MTFC_STATE_MANUAL", "MTFCMAIN_WORK_STATE__MTFC_STATE_MANUAL", 2 },
  { "MTFC_STATE_RAILWAY", "MTFCMAIN_WORK_STATE__MTFC_STATE_RAILWAY", 3 },
  { "MTFC_STATE_WALKING", "MTFCMAIN_WORK_STATE__MTFC_STATE_WALKING", 4 },
};
static const ProtobufCIntRange mtfcmain_work_state__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex mtfcmain_work_state__enum_values_by_name[5] =
{
  { "MTFC_STATE_AUTO", 1 },
  { "MTFC_STATE_MANUAL", 2 },
  { "MTFC_STATE_RAILWAY", 3 },
  { "MTFC_STATE_WALKING", 4 },
  { "MTFC_STATE_off", 0 },
};
const ProtobufCEnumDescriptor mtfcmain_work_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MTFCMainWorkState",
  "MTFCMainWorkState",
  "MTFCMainWorkState",
  "",
  5,
  mtfcmain_work_state__enum_values_by_number,
  5,
  mtfcmain_work_state__enum_values_by_name,
  1,
  mtfcmain_work_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue pin_switch_profile__enum_values_by_number[8] =
{
  { "PIN_SWITCH_ONOFF", "PIN_SWITCH_PROFILE__PIN_SWITCH_ONOFF", 0 },
  { "PIN_SWITCH_RAILWAY", "PIN_SWITCH_PROFILE__PIN_SWITCH_RAILWAY", 1 },
  { "PIN_SWITCH_WALKING", "PIN_SWITCH_PROFILE__PIN_SWITCH_WALKING", 2 },
  { "PIN_SWITCH_T1", "PIN_SWITCH_PROFILE__PIN_SWITCH_T1", 3 },
  { "PIN_SWITCH_T2", "PIN_SWITCH_PROFILE__PIN_SWITCH_T2", 4 },
  { "PIN_SWITCH_T3", "PIN_SWITCH_PROFILE__PIN_SWITCH_T3", 5 },
  { "PIN_SWITCH_T4", "PIN_SWITCH_PROFILE__PIN_SWITCH_T4", 6 },
  { "PIN_SWITCH_OP", "PIN_SWITCH_PROFILE__PIN_SWITCH_OP", 7 },
};
static const ProtobufCIntRange pin_switch_profile__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex pin_switch_profile__enum_values_by_name[8] =
{
  { "PIN_SWITCH_ONOFF", 0 },
  { "PIN_SWITCH_OP", 7 },
  { "PIN_SWITCH_RAILWAY", 1 },
  { "PIN_SWITCH_T1", 3 },
  { "PIN_SWITCH_T2", 4 },
  { "PIN_SWITCH_T3", 5 },
  { "PIN_SWITCH_T4", 6 },
  { "PIN_SWITCH_WALKING", 2 },
};
const ProtobufCEnumDescriptor pin_switch_profile__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PinSwitchProfile",
  "PinSwitchProfile",
  "PinSwitchProfile",
  "",
  8,
  pin_switch_profile__enum_values_by_number,
  8,
  pin_switch_profile__enum_values_by_name,
  1,
  pin_switch_profile__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue pin_out_profile__enum_values_by_number[8] =
{
  { "PIN_GREEN", "PIN_OUT_PROFILE__PIN_GREEN", 0 },
  { "PIN_YELLOW", "PIN_OUT_PROFILE__PIN_YELLOW", 1 },
  { "PIN_RED", "PIN_OUT_PROFILE__PIN_RED", 2 },
  { "PIN_WALKING_GREEN", "PIN_OUT_PROFILE__PIN_WALKING_GREEN", 3 },
  { "PIN_WALKING_RED", "PIN_OUT_PROFILE__PIN_WALKING_RED", 4 },
  { "PIN_OPTION_1", "PIN_OUT_PROFILE__PIN_OPTION_1", 5 },
  { "PIN_OPTION_2", "PIN_OUT_PROFILE__PIN_OPTION_2", 6 },
  { "PIN_OPTION_3", "PIN_OUT_PROFILE__PIN_OPTION_3", 7 },
};
static const ProtobufCIntRange pin_out_profile__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex pin_out_profile__enum_values_by_name[8] =
{
  { "PIN_GREEN", 0 },
  { "PIN_OPTION_1", 5 },
  { "PIN_OPTION_2", 6 },
  { "PIN_OPTION_3", 7 },
  { "PIN_RED", 2 },
  { "PIN_WALKING_GREEN", 3 },
  { "PIN_WALKING_RED", 4 },
  { "PIN_YELLOW", 1 },
};
const ProtobufCEnumDescriptor pin_out_profile__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PinOutProfile",
  "PinOutProfile",
  "PinOutProfile",
  "",
  8,
  pin_out_profile__enum_values_by_number,
  8,
  pin_out_profile__enum_values_by_name,
  1,
  pin_out_profile__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue traffic_light_state__enum_values_by_number[4] =
{
  { "TRAFFIC_LIGHT_STATE_NONE", "TRAFFIC_LIGHT_STATE__TRAFFIC_LIGHT_STATE_NONE", 0 },
  { "TRAFFIC_LIGHT_STATE_GREEN", "TRAFFIC_LIGHT_STATE__TRAFFIC_LIGHT_STATE_GREEN", 1 },
  { "TRAFFIC_LIGHT_STATE_RED", "TRAFFIC_LIGHT_STATE__TRAFFIC_LIGHT_STATE_RED", 2 },
  { "TRAFFIC_LIGHT_STATE_YELLOW", "TRAFFIC_LIGHT_STATE__TRAFFIC_LIGHT_STATE_YELLOW", 3 },
};
static const ProtobufCIntRange traffic_light_state__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex traffic_light_state__enum_values_by_name[4] =
{
  { "TRAFFIC_LIGHT_STATE_GREEN", 1 },
  { "TRAFFIC_LIGHT_STATE_NONE", 0 },
  { "TRAFFIC_LIGHT_STATE_RED", 2 },
  { "TRAFFIC_LIGHT_STATE_YELLOW", 3 },
};
const ProtobufCEnumDescriptor traffic_light_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TrafficLightState",
  "TrafficLightState",
  "TrafficLightState",
  "",
  4,
  traffic_light_state__enum_values_by_number,
  4,
  traffic_light_state__enum_values_by_name,
  1,
  traffic_light_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue walking_state__enum_values_by_number[3] =
{
  { "WALKING_STATE_OFF", "WALKING_STATE__WALKING_STATE_OFF", 0 },
  { "WALKING_STATE_GREEN", "WALKING_STATE__WALKING_STATE_GREEN", 1 },
  { "WALKING_STATE_RED", "WALKING_STATE__WALKING_STATE_RED", 2 },
};
static const ProtobufCIntRange walking_state__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex walking_state__enum_values_by_name[3] =
{
  { "WALKING_STATE_GREEN", 1 },
  { "WALKING_STATE_OFF", 0 },
  { "WALKING_STATE_RED", 2 },
};
const ProtobufCEnumDescriptor walking_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "WalkingState",
  "WalkingState",
  "WalkingState",
  "",
  3,
  walking_state__enum_values_by_number,
  3,
  walking_state__enum_values_by_name,
  1,
  walking_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
