/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: main_proto.proto */

#ifndef PROTOBUF_C_main_5fproto_2eproto__INCLUDED
#define PROTOBUF_C_main_5fproto_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "user_proto.pb-c.h"
#include "device_proto.pb-c.h"

typedef struct _MainMessage MainMessage;


/* --- enums --- */


/* --- messages --- */

struct  _MainMessage
{
  ProtobufCMessage base;
  UserMessage *usermessage;
  DeviceMessage *devicemessage;
};
#define MAIN_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&main_message__descriptor) \
    , NULL, NULL }


/* MainMessage methods */
void   main_message__init
                     (MainMessage         *message);
size_t main_message__get_packed_size
                     (const MainMessage   *message);
size_t main_message__pack
                     (const MainMessage   *message,
                      uint8_t             *out);
size_t main_message__pack_to_buffer
                     (const MainMessage   *message,
                      ProtobufCBuffer     *buffer);
MainMessage *
       main_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   main_message__free_unpacked
                     (MainMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MainMessage_Closure)
                 (const MainMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor main_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_main_5fproto_2eproto__INCLUDED */
